# Generated by Django 3.2.5 on 2021-07-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_title', models.CharField(max_length=50)),
                ('expedition_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_title', models.CharField(max_length=50)),
                ('hook_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('itinerary_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_type', models.IntegerField(choices=[('Included', 0), ('Excluded', 1)])),
            ],
        ),
        migrations.CreateModel(
            name='PakageInclusionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('package_inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski.packageinclusion')),
            ],
        ),
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ski',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200, unique=True)),
                ('expedition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ski.expeditioninfo')),
                ('hook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ski.hook')),
                ('package_inclusion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ski.packageinclusion')),
                ('pricing_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ski.pricinginfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Simple',
        ),
        migrations.AddField(
            model_name='itineraryinfo',
            name='ski',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
    ]
