# Generated by Django 3.2.5 on 2021-07-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0002_auto_20210726_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ski',
            old_name='hook',
            new_name='hook_id',
        ),
        migrations.AddField(
            model_name='hook',
            name='ski_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='ski',
            name='expedition',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.expeditioninfo'),
        ),
    ]
