# Generated by Django 3.2.5 on 2021-07-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0003_auto_20210726_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hook',
            name='ski_id',
        ),
        migrations.RemoveField(
            model_name='ski',
            name='hook_id',
        ),
        migrations.AddField(
            model_name='hook',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
    ]
