# Generated by Django 3.2.5 on 2021-07-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0004_auto_20210726_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ski',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='ski',
            name='package_inclusion',
        ),
        migrations.RemoveField(
            model_name='ski',
            name='pricing_info',
        ),
        migrations.AddField(
            model_name='expeditioninfo',
            name='expedition',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AddField(
            model_name='pricinginfo',
            name='pricing_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='pakageinclusiondetail',
            name='package_inclusion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
    ]
