# Generated by Django 3.2.5 on 2021-07-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0005_auto_20210726_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expeditioninfo',
            old_name='expedition',
            new_name='ski',
        ),
        migrations.RenameField(
            model_name='pricinginfo',
            old_name='pricing_info',
            new_name='ski',
        ),
        migrations.AddField(
            model_name='pakageinclusiondetail',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='included_type',
            field=models.IntegerField(choices=[(0, 'Included'), (1, 'Excluded')]),
        ),
        migrations.AlterField(
            model_name='pakageinclusiondetail',
            name='package_inclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ski.packageinclusion'),
        ),
    ]
