# Generated by Django 3.2.5 on 2021-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0006_auto_20210726_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakageinclusiondetail',
            name='package_inclusion',
        ),
        migrations.AddField(
            model_name='pakageinclusiondetail',
            name='included_type',
            field=models.IntegerField(choices=[(0, 'Included'), (1, 'Excluded')], default=0),
        ),
        migrations.DeleteModel(
            name='PackageInclusion',
        ),
    ]
