# Generated by Django 3.2.5 on 2021-07-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0007_auto_20210726_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakageinclusiondetail',
            name='included_type',
        ),
        migrations.RemoveField(
            model_name='pakageinclusiondetail',
            name='ski',
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_type', models.IntegerField(choices=[(0, 'Included'), (1, 'Excluded')], default=0)),
                ('ski', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski')),
            ],
        ),
        migrations.AddField(
            model_name='pakageinclusiondetail',
            name='package_inclusion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.packageinclusion'),
        ),
    ]
