# Generated by Django 3.2.5 on 2021-07-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0008_auto_20210726_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakageinclusiondetail',
            name='package_inclusion',
        ),
        migrations.AddField(
            model_name='pakageinclusiondetail',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AddField(
            model_name='ski',
            name='included_type',
            field=models.IntegerField(choices=[(0, 'Included'), (1, 'Excluded')], default=0),
        ),
        migrations.DeleteModel(
            name='PackageInclusion',
        ),
    ]
