# Generated by Django 3.2.5 on 2021-07-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0009_auto_20210726_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pakageinclusiondetail',
            name='ski',
        ),
        migrations.RemoveField(
            model_name='ski',
            name='included_type',
        ),
        migrations.CreateModel(
            name='PackageInclustionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_type', models.IntegerField(choices=[(0, 'Included'), (1, 'Excluded')], default=0)),
                ('ski', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski')),
            ],
        ),
        migrations.AddField(
            model_name='pakageinclusiondetail',
            name='package_inclusion_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.packageinclustiontype'),
        ),
    ]
