# Generated by Django 3.2.5 on 2021-07-26 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0010_auto_20210726_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inclusion_decription', models.TextField()),
                ('ski', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski')),
            ],
        ),
        migrations.RenameModel(
            old_name='PakageInclusionDetail',
            new_name='PackageExclusion',
        ),
        migrations.RenameField(
            model_name='packageexclusion',
            old_name='description',
            new_name='exclusion_decription',
        ),
        migrations.RemoveField(
            model_name='packageexclusion',
            name='package_inclusion_type',
        ),
        migrations.AddField(
            model_name='packageexclusion',
            name='ski',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.DeleteModel(
            name='PackageInclustionType',
        ),
    ]
