# Generated by Django 3.2.5 on 2021-07-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0011_auto_20210726_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ski',
            options={'verbose_name': 'Ski Expedition Package'},
        ),
    ]
