# Generated by Django 3.2.5 on 2021-07-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0012_alter_ski_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageexclusion',
            options={'verbose_name': 'List what is excluded in ski package', 'verbose_name_plural': 'List what are excluded in ski package'},
        ),
        migrations.AlterModelOptions(
            name='ski',
            options={'verbose_name': 'Ski Expedition Package', 'verbose_name_plural': 'Ski Expedition Packages'},
        ),
    ]
