# Generated by Django 3.2.5 on 2021-07-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0013_auto_20210727_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditioninfo',
            options={'verbose_name': 'Title of the Expedition with short description'},
        ),
        migrations.AlterModelOptions(
            name='hook',
            options={'verbose_name': 'Catchy Hook for expedition'},
        ),
        migrations.AlterModelOptions(
            name='itineraryinfo',
            options={'verbose_name': 'List Itinerary info about this package'},
        ),
        migrations.AlterModelOptions(
            name='packageinclusion',
            options={'verbose_name': 'List what is included in ski package', 'verbose_name_plural': 'List what are included in ski package'},
        ),
        migrations.AlterModelOptions(
            name='pricinginfo',
            options={'verbose_name': 'Price of the package and nearest available date for it'},
        ),
    ]
