# Generated by Django 3.2.5 on 2021-07-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0014_auto_20210727_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryinfo',
            name='end',
            field=models.PositiveIntegerField(verbose_name='End Day'),
        ),
        migrations.AlterField(
            model_name='itineraryinfo',
            name='start',
            field=models.PositiveIntegerField(verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='available_date',
            field=models.DateTimeField(verbose_name='Available Date (A.D.)'),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price in USD'),
        ),
    ]
