# Generated by Django 3.2.5 on 2021-07-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0015_auto_20210727_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryinfo',
            name='end',
            field=models.PositiveIntegerField(default=None, verbose_name='End Day'),
        ),
    ]
