# Generated by Django 3.2.5 on 2021-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0016_alter_itineraryinfo_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryinfo',
            name='end',
            field=models.PositiveIntegerField(blank=True, verbose_name='End Day'),
        ),
    ]
