# Generated by Django 3.2.5 on 2021-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0017_alter_itineraryinfo_end'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricinginfo',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', '0')), name='product_price_non_negative'),
        ),
    ]
