# Generated by Django 3.2.5 on 2021-07-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0018_pricinginfo_product_price_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricinginfo',
            name='product_price_non_negative',
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='available_date',
            field=models.DateField(verbose_name='Available Date (A.D.)'),
        ),
        migrations.AddConstraint(
            model_name='pricinginfo',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 18)), name='age_gte_18'),
        ),
    ]
