# Generated by Django 3.2.5 on 2021-07-27 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0019_auto_20210727_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricinginfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price in USD'),
        ),
    ]
