# Generated by Django 3.2.5 on 2021-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0021_alter_pricinginfo_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricinginfo',
            name='age_gte_18',
        ),
        migrations.AddConstraint(
            model_name='pricinginfo',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='price_gte_0'),
        ),
    ]
