# Generated by Django 3.2.5 on 2021-07-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0024_alter_expeditioninfo_ski'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditioninfo',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='hook',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
    ]
