# Generated by Django 3.2.5 on 2021-07-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0026_alter_itineraryinfo_ski'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditioninfo',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_info', to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='itineraryinfo',
            name='ski',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_info', to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='packageexclusion',
            name='ski',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='package_exclusion', to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='ski',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='package_inclusion', to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='ski',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_info', to='ski.ski'),
        ),
    ]
