# Generated by Django 3.2.5 on 2021-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treknav',
            name='first_nav_item',
            field=models.CharField(default='<QuerySet [<ExpeditionInfo: hfakljfhalk>]>', max_length=1500),
        ),
    ]
