# Generated by Django 3.2.5 on 2021-10-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_alter_treknav_first_nav_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treknav',
            name='first_nav_item',
            field=models.CharField(choices=[('hfakljfhalk', 'HFAKLJFHALK'), ('Mt eve', 'MT EVE')], max_length=1500),
        ),
    ]
