# Generated by Django 3.2.5 on 2021-10-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski', '0029_alter_itineraryinfo_end'),
        ('navigation', '0006_auto_20211011_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treknav',
            old_name='first_nav_item',
            new_name='trek_nav_item',
        ),
        migrations.CreateModel(
            name='SkiNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ski_nav_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.expeditioninfo')),
            ],
        ),
    ]
