# Generated by Django 3.2.5 on 2021-10-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0004_alter_itineraryinfo_end'),
        ('ski', '0029_alter_itineraryinfo_end'),
        ('navigation', '0007_auto_20211011_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinav',
            name='ski_nav_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ski.ski'),
        ),
        migrations.AlterField(
            model_name='treknav',
            name='trek_nav_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trek.trek'),
        ),
    ]
