# Generated by Django 3.2.5 on 2021-10-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_auto_20211011_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treknav',
            old_name='trek_nav_item',
            new_name='name',
        ),
    ]
