# Generated by Django 3.2.5 on 2021-10-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_rename_trek_nav_item_treknav_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treknav',
            old_name='name',
            new_name='trek_nav_item',
        ),
    ]
