# Generated by Django 3.2.5 on 2021-10-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_rename_name_treknav_trek_nav_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treknav',
            options={'verbose_name': 'Trek packages to show in Navigation'},
        ),
    ]
