# Generated by Django 3.2.5 on 2021-07-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hook',
            options={'verbose_name': 'Catchy Hook for expedition'},
        ),
    ]
