# Generated by Django 3.2.5 on 2021-07-29 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0002_alter_hook_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expeditioninfo',
            options={'verbose_name': 'Title of the Expedition with short description'},
        ),
        migrations.AlterModelOptions(
            name='itineraryinfo',
            options={'verbose_name': 'List Ininerary info about this package'},
        ),
        migrations.AlterModelOptions(
            name='packageexclusion',
            options={'verbose_name': 'List what is excluded in trek package', 'verbose_name_plural': 'List what are excluded in trek package'},
        ),
        migrations.AlterModelOptions(
            name='packageinclusion',
            options={'verbose_name': 'List what is included in trek package', 'verbose_name_plural': 'List what are included in trek package'},
        ),
        migrations.AlterModelOptions(
            name='pricinginfo',
            options={'verbose_name': 'Price of the package and nearest available date for it'},
        ),
        migrations.AlterModelOptions(
            name='trek',
            options={'verbose_name': 'Trek Expedition Package', 'verbose_name_plural': 'Trek Expedition Packages'},
        ),
        migrations.AlterField(
            model_name='expeditioninfo',
            name='trek',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expedition_info', to='trek.trek'),
        ),
        migrations.AlterField(
            model_name='itineraryinfo',
            name='end',
            field=models.PositiveIntegerField(blank=True, verbose_name='End Day'),
        ),
        migrations.AlterField(
            model_name='itineraryinfo',
            name='start',
            field=models.PositiveIntegerField(verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='itineraryinfo',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_info', to='trek.trek'),
        ),
        migrations.AlterField(
            model_name='packageexclusion',
            name='trek',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='package_exclusion', to='trek.trek'),
        ),
        migrations.AlterField(
            model_name='packageinclusion',
            name='trek',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='package_inclusion', to='trek.trek'),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='available_date',
            field=models.DateField(verbose_name='Available Date (A.D.)'),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price in USD'),
        ),
        migrations.AlterField(
            model_name='pricinginfo',
            name='trek',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_info', to='trek.trek'),
        ),
        migrations.AddConstraint(
            model_name='pricinginfo',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='trek_price_gte_0'),
        ),
    ]
